# Generated by Django 3.2.9 on 2021-11-08 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlist',
            name='user',
        ),
        migrations.AddField(
            model_name='friendlist',
            name='profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='account.profile'),
            preserve_default=False,
        ),
    ]
