# Generated by Django 3.2.9 on 2021-11-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_friendlist_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='account.Profile'),
        ),
        migrations.DeleteModel(
            name='FriendList',
        ),
    ]
