# Generated by Django 3.2.9 on 2021-11-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_participators'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='finish',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.CharField(max_length=5),
        ),
    ]
