# Generated by Django 3.2.9 on 2021-11-14 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20211114_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.CreateModel(
            name='EventInviteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='events.event')),
                ('to_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_event', to='events.event')),
            ],
        ),
    ]
