# Generated by Django 3.2.9 on 2021-11-14 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20211110_1335'),
        ('events', '0004_auto_20211114_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinviterequest',
            name='from_user',
        ),
        migrations.AddField(
            model_name='eventinviterequest',
            name='from_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='from_creator', to='account.profile'),
            preserve_default=False,
        ),
    ]
