# Generated by Django 3.2.9 on 2021-11-14 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20211110_1335'),
        ('events', '0006_auto_20211114_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinviterequest',
            name='to_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_profile', to='account.profile'),
        ),
    ]
