# Generated by Django 3.2.9 on 2021-11-25 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_user'),
        ('events', '0009_event_privat_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='account.profile', verbose_name='event creator'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='event description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='finish',
            field=models.CharField(max_length=5, verbose_name='time event finish'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participators',
            field=models.ManyToManyField(blank=True, to='account.Profile', verbose_name='event participators'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start',
            field=models.CharField(max_length=5, verbose_name='time event starts'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='event title'),
        ),
        migrations.AlterField(
            model_name='eventinviterequest',
            name='from_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_event', to='events.event'),
        ),
        migrations.AlterField(
            model_name='eventinviterequest',
            name='to_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_profile', to='account.profile'),
        ),
    ]
