# Generated by Django 3.2.7 on 2022-01-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcreationactivity',
            options={'verbose_name_plural': 'Event creation activities'},
        ),
    ]
